name: Calcolo Algoritmico e Deploy Hugging Face

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # Esegue l'analisi Python automaticamente ogni ora

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Controlla il codice
      uses: actions/checkout@v4

    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installa librerie necessarie
      run: |
        pip install pandas yfinance requests

    - name: Esegui main.py (Generazione analisi.json)
      run: python main.py

    - name: Invia file aggiornati su Hugging Face Spaces
      uses: huggingface/hub-sync@v0.1.0
      with:
        github_repo_id: ${{ github.repository }}
        huggingface_repo_id: VINCITN/chip-monitor
        hf_token: ${{ secrets.HF_TOKEN }}
        repo_type: space
        space_sdk: static
